<?php
namespace app\index\controller;

use think\App;

class Common extends Api
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //echo 111;
    }

    private function test()
    {

    }

}